---
- hosts: servers
  become: yes
  tasks:

    - name: update system
      apt:
          update_cache: Yes
    
    - name: installing docker package
      apt:
       pkg:
         - apt-transport-https 
         - ca-certificates
         - curl
         - software-properties-common
         - python3-pip
         - virtualenv
         - python3-setuptools
       state: latest

    - name: Add docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Install docker
      apt:
        name: docker-ce
        state: latest

    - name: Install docker for pip
      ansible.builtin.pip:
        name: docker

    - name: Run Node-RED in Docker
      become: true
      command: docker run -it -d -p 1880:1880 --name mynodered nodered/node-red

    - name: add node-red-node-mysql to node-red
      community.docker.docker_container_exec: 
        container: mynodered
        command: npm i node-red-node-mysql
      register: result

    - name: restart container mynodered
      community.docker.docker_container:
        name: mynodered
        image: nodered/node-red
        state: started
        restart: yes