---
- hosts: raspberrypi1
  become: true
  collections:
   - community.general
   - community.docker
  tasks:

    - name: Run Node-RED in Docker
      become: true
      command: docker run -it -d -p 1880:1880 --name mynodered nodered/node-red

    - name: pull docker image
      community.docker.docker_image:
        name: mysql
        source: pull
        tag: latest

    - name: Run mysql in Docker
      become: true
      command: docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=Ubuntu -d mysql

    - name: add node red node mysql to node red
      community.docker.docker_container_exec:
        container: mynodered
        command: npm i node-red-node-mysql
      register: result

    - name: restart container mynodered
      community.docker.docker_container:
        name: mynodered
        image: nodered/node-red
        state: started
        restart: yes