---
- hosts: servers
  become: yes
  tasks:

    - name: update system
      apt:
          update_cache: Yes
    
    - name: installing docker package
      apt:
       pkg:
         - apt-transport-https 
         - ca-certificates
         - curl
         - software-properties-common
       state: latest

    - name: Add docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Install docker
      apt:
        name: docker-ce
        state: latest

    - name: Run Node-RED in Docker
      become: true
      command: docker run -it -d -p 1880:1880 --name mynodered nodered/node-red
