---
- hosts: raspberrypi1
  become: true
  collections:
   - community.general
   - community.docker
  tasks:

    - name: Run Node-RED in Docker
      become: true
      command: docker run -it -d -p 1880:1880 --name mynodered nodered/node-red

    - name: pull docker image
      community.docker.docker_image:
        name: mysql
        source: pull
        tag: latest

    - name: Run mysql in Docker
      become: true
      command: docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=Ubuntu -d mysql

    - name: add node red node mysql to node red
      community.docker.docker_container_exec:
        container: mynodered
        command: npm i node-red-node-mysql
      register: result

    - name: restart container mynodered
      community.docker.docker_container:
        name: mynodered
        image: nodered/node-red
        state: started
        restart: yes

    - name: get new version npm
      become: true
      command: npm install -g n
    
    - name: install new version npm
      become: true
      command: n 14.21.2

    - name: clone github repository
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/joris-zwering/Os-project-front-end'
        dest: /etc/application/
        clone: yes
        update: no

    - name: install npm
      become: true
      command: chdir=/etc/application npm install

    - name: Run development server
      become: true
      command: npm install pm2 -g

    - name: Go to the folder and execute command
      become: true
      command: chdir=/etc/application pm2 start "npm run dev" --name Fronted-end

    - name: Go to the folder and execute command
      become: true
      command: chdir=/etc/application pm2 start "npx prisma studio" --name prisma

    
    




